"""Add achievement_reward and event_reward tables

Revision ID: 3f48e653da0f
Revises: 9119a2330d8d
Create Date: 2024-10-26 18:09:56.186863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f48e653da0f'
down_revision: Union[str, None] = '9119a2330d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reward_achievement', 'reward_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reward_achievement', 'achievement_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reward_achievement', 'id')
    op.alter_column('user_achievement', 'achievement_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_achievement', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_achievement', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_achievement', 'achievement_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('reward_achievement', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('reward_achievement', 'achievement_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reward_achievement', 'reward_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
