"""empty message

Revision ID: 9af706d072e6
Revises: 51ed077f5d36
Create Date: 2024-10-27 05:07:19.359387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af706d072e6'
down_revision: Union[str, None] = '51ed077f5d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievement', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user_achievement', sa.Column('progress', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_achievement', 'progress')
    op.alter_column('achievement', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
