"""Add achievement_reward and event_reward tables

Revision ID: cb9fddc5ab76
Revises: 3f48e653da0f
Create Date: 2024-10-26 18:48:11.914611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import JSON

# revision identifiers, used by Alembic.
revision: str = 'cb9fddc5ab76'
down_revision: Union[str, None] = '3f48e653da0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    role_table = sa.table(
        'role',
        sa.Column('name', sa.String, nullable=False),
        sa.Column('permissions', JSON, nullable=True)
    )

    # Выполняем bulk insert
    op.bulk_insert(
        role_table,
        [
            {
                "name": "user",
                "permissions": {}  # Пустое JSON-значение для permissions
            },
            {
                "name": "admin",
                "permissions": {}  # Пустое JSON-значение для permissions
            }
        ]
    )
    reward_table = sa.table(
        'reward',
        sa.Column('title', sa.String),
        sa.Column('file_path', sa.String),
        sa.Column('is_market_available', sa.Boolean),
        sa.Column('market_cost', sa.Float)
    )
    op.bulk_insert(
        reward_table,
        [
            {
                "title": "leaf",
                "file_path": "http://localhost:9000/rewards/leaf.svg",
                "is_market_available": False,
                "market_cost": None
            },
            {
                "title": "xp",
                "file_path": None,
                "is_market_available": False,
                "market_cost": None
            }
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
